# command line: pre-proccess.py

config: ./config/st_gcn/kinetics-skeleton/demo.yaml
device:
- 0
height: 1080
ignore_weights: []
model: net.st_gcn.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: openpose
        strategy: spatial
    in_channels: 3
    num_class: 400
model_fps: 30
openpose: 3dparty/openpose/build
output_dir: ./data/demo_result
print_log: false
save_log: true
use_gpu: true
video: ./resource/media/kkkk.mp4
weights: ./models/st_gcn.kinetics.pt
work_dir: ./work_dir/tmp
